# Generated by Django 5.1.1 on 2024-09-27 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_examinationresult_course_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="is_admin",
            new_name="is_staff",
        ),
    ]
